<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinyclub.proto

namespace Tinyclub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinyclub.GetInviteLinkReply</code>
 */
class GetInviteLinkReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>string invite_link = 3;</code>
     */
    protected $invite_link = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $message
     *     @type string $invite_link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tinyclub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invite_link = 3;</code>
     * @return string
     */
    public function getInviteLink()
    {
        return $this->invite_link;
    }

    /**
     * Generated from protobuf field <code>string invite_link = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInviteLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->invite_link = $var;

        return $this;
    }

}

