<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinyclub.proto

namespace Tinyclub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinyclub.InitDiscordGuildRequest</code>
 */
class InitDiscordGuildRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 guild_id = 1;</code>
     */
    protected $guild_id = 0;
    /**
     * Generated from protobuf field <code>string club_unique_name = 2;</code>
     */
    protected $club_unique_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $guild_id
     *     @type string $club_unique_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tinyclub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 guild_id = 1;</code>
     * @return int|string
     */
    public function getGuildId()
    {
        return $this->guild_id;
    }

    /**
     * Generated from protobuf field <code>uint64 guild_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuildId($var)
    {
        GPBUtil::checkUint64($var);
        $this->guild_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string club_unique_name = 2;</code>
     * @return string
     */
    public function getClubUniqueName()
    {
        return $this->club_unique_name;
    }

    /**
     * Generated from protobuf field <code>string club_unique_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClubUniqueName($var)
    {
        GPBUtil::checkString($var, True);
        $this->club_unique_name = $var;

        return $this;
    }

}

