<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinyclub.proto

namespace Tinyclub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinyclub.InitDiscordGuildReply</code>
 */
class InitDiscordGuildReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject notify_webhook = 3;</code>
     */
    protected $notify_webhook = null;
    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject admin_notify_webhook = 4;</code>
     */
    protected $admin_notify_webhook = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $message
     *     @type \Tinyclub\WebhookObject $notify_webhook
     *     @type \Tinyclub\WebhookObject $admin_notify_webhook
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tinyclub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject notify_webhook = 3;</code>
     * @return \Tinyclub\WebhookObject|null
     */
    public function getNotifyWebhook()
    {
        return $this->notify_webhook;
    }

    public function hasNotifyWebhook()
    {
        return isset($this->notify_webhook);
    }

    public function clearNotifyWebhook()
    {
        unset($this->notify_webhook);
    }

    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject notify_webhook = 3;</code>
     * @param \Tinyclub\WebhookObject $var
     * @return $this
     */
    public function setNotifyWebhook($var)
    {
        GPBUtil::checkMessage($var, \Tinyclub\WebhookObject::class);
        $this->notify_webhook = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject admin_notify_webhook = 4;</code>
     * @return \Tinyclub\WebhookObject|null
     */
    public function getAdminNotifyWebhook()
    {
        return $this->admin_notify_webhook;
    }

    public function hasAdminNotifyWebhook()
    {
        return isset($this->admin_notify_webhook);
    }

    public function clearAdminNotifyWebhook()
    {
        unset($this->admin_notify_webhook);
    }

    /**
     * Generated from protobuf field <code>.tinyclub.WebhookObject admin_notify_webhook = 4;</code>
     * @param \Tinyclub\WebhookObject $var
     * @return $this
     */
    public function setAdminNotifyWebhook($var)
    {
        GPBUtil::checkMessage($var, \Tinyclub\WebhookObject::class);
        $this->admin_notify_webhook = $var;

        return $this;
    }

}

