<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinyclub.proto

namespace Tinyclub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tinyclub.WebhookObject</code>
 */
class WebhookObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 guild_id = 2;</code>
     */
    protected $guild_id = 0;
    /**
     * Generated from protobuf field <code>uint64 channel_id = 3;</code>
     */
    protected $channel_id = 0;
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string token = 5;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $guild_id
     *     @type int|string $channel_id
     *     @type string $name
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tinyclub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 guild_id = 2;</code>
     * @return int|string
     */
    public function getGuildId()
    {
        return $this->guild_id;
    }

    /**
     * Generated from protobuf field <code>uint64 guild_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuildId($var)
    {
        GPBUtil::checkUint64($var);
        $this->guild_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 channel_id = 3;</code>
     * @return int|string
     */
    public function getChannelId()
    {
        return $this->channel_id;
    }

    /**
     * Generated from protobuf field <code>uint64 channel_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkUint64($var);
        $this->channel_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 5;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

